<a href="https://colab.research.google.com/github/VanjariAbhinay/aws-free-tier-app/blob/main/Introduction_to_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import time

##**Python List**

###**Calculating the square of each element**

In [2]:
start = time.time()

list1 = list(range(100_000_000))

for i in list1:
  i*=i

end = time.time()
list_time = end - start

print(f"Time taken using List: {list_time:.6f} seconds")


Time taken using List: 21.797889 seconds


##**NumPy Arrays**

###**Calculating the square of each element**

In [10]:
import numpy as np

start = time.time()

numpy_array = np.arange(100_000_000)
numpy_array = numpy_array**2

end = time.time()
numpy_time = end - start

print(f"Time taken using NumPy: {numpy_time:.6f} seconds")


Time taken using NumPy: 0.586784 seconds


##**Speedup Calculation:Lists vs. Numpy Arrays**

In [11]:
speedup = list_time / numpy_time

In [12]:
speedup

37.14804083616128

# NumPy
- Short for Numerical Python
- Foundational Package for Numerical computing in python
- Provides an ndarray object which is an efficient multidimensional array providing fast array oriented operations
- Provides a lot of functions

##**1D Array Creation Methods**

###**From List**

You can create a NumPy array directly from a Python list using np.array()

*syntax* : np.arange([list of elements])

In [ ]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

###**Using built-in methods**

NumPy provides several built-in methods to create arrays quickly:



**Zeros** : Creates an array filled with zeros of the specified size

*syntax* : np.zeros(shape)


In [ ]:
np.zeros(3)

array([0., 0., 0.])

**Ones** : Creates an array filled with ones of the specified size

*syntax* : np.ones(shape)


In [ ]:
np.ones(1)

array([1.])

Random:
Creates an array of random floats between 0 and 1

*syntax* : np.random.random(shape)

In [ ]:
np.random.random(3)

array([0.4439518 , 0.29526533, 0.14114682])

arange : Creates an array with a fixed step size betwen values

*syntax* : np.arange(start, stop, step)

start is inclusive

stop is exclusive

default value of step is 1


In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

**linspace** : Creates an array of evenly spaced values between two numbers

*syntax* : np.linspace(start, stop, num)

start is inclusive

stop is inclusive

In [ ]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])